/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/shoe.glb --typescript 
Author: quaz30 (https://sketchfab.com/quaz30)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-air-zoom-pegasus-36-00fd99e778c244c3bd3b65f99dad7cb2
Title: Nike Air Zoom Pegasus 36
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useStore } from '@/store/useStore'
import * as THREE from 'three'
// import { useFrames } from 'next/dist/next-devtools/dev-overlay/utils/get-error-by-type'

export const Shoe = (props: any) =>  {
  const { nodes, materials } = useGLTF('/shoe.glb')
  const groupRef = useRef<THREE.Group>(null!) // Ссылка на группу объектов
  const color = useStore((state) => state.color)
  const { defaultMaterial } = nodes

  // Эта функция запускается 60 раз в секунду
//   useFrame((state, delta) => {
//     // delta — это время между кадрами (чтобы скорость была одинаковой везде)
//     groupRef.current.rotation.y += delta * 0.5 // Вращаем по вертикальной оси
//   })

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh 
            geometry={(defaultMaterial as any).geometry} 
            material={materials.NikeShoe} 
            material-color={color} // Теперь кроссовок меняет цвет!
            rotation={[Math.PI / 2, 0, 0]} 
        />
      </group>
    </group>
  )
}

useGLTF.preload('/shoe.glb')
